# Generated by Django 4.1 on 2024-06-16 21:20
# Сгенерировано Django 4.1 16 июня 2024 г. в 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        # Зависимости от предыдущих миграций: 'contenttypes' с удаленным 'content_type_name'
        # и 'store' с начальной миграцией '0001_initial'
        ("contenttypes", "0002_remove_content_type_name"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggeditem",  # Модель TaggedItem
            name="content_type",  # Поле content_type
            field=models.ForeignKey(
                # Установка каскадного удаления для связи
                on_delete=django.db.models.deletion.CASCADE,
                # Обратное имя связанной модели
                related_name="%(app_label)s_%(class)s_tagged_items",
                to="contenttypes.contenttype",  # Связь с моделью ContentType
                verbose_name="content type",  # Отображаемое имя поля
            ),
        ),
    ]
