# Generated by Django 4.2 on 2025-01-03 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_changehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True,
                                           blank=True,
                                           db_index=True,
                                           verbose_name="ID"),
                ),
                ("title",
                 models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("slug", models.CharField(db_index=True, max_length=50)),
                (
                    "pub_date",
                    models.DateTimeField(blank=True,
                                         editable=False,
                                         verbose_name="Дата добавления"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2,
                                        max_digits=8,
                                        verbose_name="Новая цена"),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "image",
                    models.TextField(blank=True,
                                     max_length=100,
                                     verbose_name="Изображение"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                ("history_id",
                 models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason",
                 models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"),
                                 ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Товар",
                "verbose_name_plural": "historical Товары",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
