# Generated by Django 4.2 on 2025-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_historicalitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
