# Generated by Django 3.2.10 on 2024-06-16 14:58

from django.conf import settings  # Импорт настроек Django
# Импорт модулей миграций и моделей Django
from django.db import migrations, models
import django.db.models.deletion  # Импорт типа удаления моделей Django


class Migration(migrations.Migration):
    initial = True  # Указываем, что это начальная миграция

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL),  # Зависимость от настройки пользователя
        (
            "checkout",
            "0001_initial",
        ),  # Зависимость от предыдущей миграции в приложении checkout
        (
            "store",
            "0001_initial",
        ),  # Зависимость от начальной миграции в приложении store
    ]  # Список зависимостей для миграции

    operations = [
        migrations.AddField(
            model_name="orderitem",  # Имя модели OrderItem
            name="item",  # Название поля
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.item",
                verbose_name="Товар",
            ),  # Внешний ключ к модели Item из приложения store
        ),
        migrations.AddField(
            model_name="orderitem",  # Имя модели OrderItem
            name="order",  # Название поля
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="checkout.order",
                verbose_name="Заказ",
            ),  # Внешний ключ к модели Order из текущего приложения с обратной связью items
        ),
        migrations.AddField(
            model_name="order",  # Имя модели Order
            name="user",  # Название поля
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),  # Внешний ключ к модели пользователя Django с обратной связью orders
        ),
    ]  # Операции миграции, добавление внешних ключей и полей
