# Generated by Django 3.2.10 on 2024-06-16 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True  # Эта миграция является начальной

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),  # Зависимость от модели пользователя Django
        (
            "cart",
            "0001_initial",
        ),  # Зависимость от предыдущей миграции приложения 'cart'
        (
            "store",
            "0001_initial",
        ),  # Зависимость от предыдущей миграции приложения 'store'
    ]

    operations = [
        # Добавление поля 'item' к модели 'CartItem'
        migrations.AddField(
            model_name="cartitem",  # Имя модели, к которой добавляется поле
            name="item",  # Название добавляемого поля
            field=models.ForeignKey(  # Определение поля в виде внешнего ключа
                on_delete=django.db.models.deletion.CASCADE,
                # Поведение при удалении связанного объекта (удалить CartItem)
                to="store.item",  # Ссылка на модель 'Item' из приложения 'store'
                verbose_name="Товар",  # Человекочитаемое название поля
            ),
        ),
        # Добавление поля 'user' к модели 'Cart'
        migrations.AddField(
            model_name="cart",  # Имя модели, к которой добавляется поле
            name="user",  # Название добавляемого поля
            field=models.ForeignKey(  # Определение поля в виде внешнего ключа
                on_delete=django.db.models.deletion.CASCADE,
                # Поведение при удалении связанного объекта (удалить Cart)
                related_name="carts",
                # Имя обратной связи для доступа к корзинам из объектов
                # пользователя
                to=settings.
                AUTH_USER_MODEL,  # Ссылка на модель пользователя Django
                verbose_name="Покупатель",  # Человекочитаемое название поля
            ),
        ),
    ]
