# Generated by Django 4.1 on 2024-06-16 21:20

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('store', '0001_initial'),  # Зависимость от первой миграции приложения 'store'
        ('cart', '0002_initial'),   # Зависимость от второй миграции приложения 'cart'
    ]

    operations = [
        # Добавление M2M-поля 'items' к модели 'Cart'
        migrations.AddField(
            model_name='cart',  # Имя модели, к которой добавляется поле
            name='items',      # Название добавляемого поля
            field=models.ManyToManyField(  # Определение поля как Many-to-Many (многие ко многим)
                related_name='carts',      # Имя обратной связи для доступа к корзинам из объектов товаров
                through='cart.CartItem',   # Промежуточная модель для связи
                to='store.item',           # Ссылка на модель 'Item' из приложения 'store'
                verbose_name='Товары',     # Человекочитаемое название поля
            ),
        ),

        # Изменение внешнего ключа 'cart' в модели 'CartItem'
        migrations.AlterField(
            model_name='cartitem',  # Имя модели, у которой изменяется поле
            name='cart',           # Название изменяемого поля
            field=models.ForeignKey(  # Определение поля в виде внешнего ключа
                on_delete=django.db.models.deletion.CASCADE,  # Поведение при удалении связанного объекта (удалить CartItem)
                related_name='cart_items',  # Имя обратной связи для доступа к CartItem из объектов корзины
                to='cart.cart',             # Ссылка на модель 'Cart' из приложения 'cart'
                verbose_name='Корзина',     # Человекочитаемое название поля
            ),
        ),

        # Изменение внешнего ключа 'item' в модели 'CartItem'
        migrations.AlterField(
            model_name='cartitem',  # Имя модели, у которой изменяется поле
            name='item',            # Название изменяемого поля
            field=models.ForeignKey(  # Определение поля в виде внешнего ключа
                on_delete=django.db.models.deletion.CASCADE,  # Поведение при удалении связанного объекта (удалить CartItem)
                related_name='cart_items',  # Имя обратной связи для доступа к CartItem из объектов товара
                to='store.item',            # Ссылка на модель 'Item' из приложения 'store'
                verbose_name='Товар',       # Человекочитаемое название поля
            ),
        ),
    ]
