# Generated by Django 4.1 on 2024-06-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "store",
            "0002_alter_taggeditem_content_type",
        ),  # Зависимость от миграции '0002_alter_taggeditem_content_type' из приложения 'store'
        (
            "cart",
            "0003_cart_items_alter_cartitem_cart_alter_cartitem_item",
        ),  # Зависимость от предыдущей миграции '0003_cart_items_alter_cartitem_cart_alter_cartitem_item' из приложения 'cart'
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",  # Имя модели, у которой изменяется поле
            name="item",  # Название изменяемого поля
            field=models.ForeignKey(  # Определение поля в виде внешнего ключа
                on_delete=django.db.models.deletion.CASCADE,
                # Поведение при удалении связанного объекта (удалить CartItem)
                to="store.item",  # Ссылка на модель 'Item' из приложения 'store'
                verbose_name="Товар",  # Человекочитаемое название поля
            ),
        ),
    ]
